"""Add budget_usd to rate limits

Revision ID: 5b199b57852b
Revises: cd01f7ebba3c
Create Date: 2026-07-13 08:17:32.946308+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b199b57852b'
down_revision: Union[str, None] = 'cd01f7ebba3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_alerts_sent', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_api_keys', 'user_id',
               existing_type=sa.UUID(),
               server_default='00000000-0000-0000-0000-000000000000',
               existing_nullable=False)
    op.alter_column('ai_api_keys', 'encrypted_key',
               existing_type=sa.TEXT(),
               comment='Fernet-encrypted provider API key. Never store plaintext here.',
               existing_nullable=False)
    op.alter_column('ai_api_keys', 'label',
               existing_type=sa.VARCHAR(length=200),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_api_keys', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_job_runs', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_provider_reported_usage', 'period_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Start of the usage period (UTC).',
               existing_nullable=False)
    op.alter_column('ai_provider_reported_usage', 'period_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='End of the usage period (UTC).',
               existing_nullable=False)
    op.alter_column('ai_provider_reported_usage', 'total_tokens',
               existing_type=sa.INTEGER(),
               comment='Total tokens for the period as reported by the provider.',
               existing_nullable=True)
    op.alter_column('ai_provider_reported_usage', 'total_cost',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment='Total cost (USD) as reported by the provider.',
               existing_nullable=True)
    op.alter_column('ai_provider_reported_usage', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this record was fetched from the provider API.',
               existing_nullable=False)
    op.alter_column('ai_provider_reported_usage', 'source',
               existing_type=sa.VARCHAR(length=200),
               server_default=None,
               comment='Which endpoint/method was used to fetch this data.',
               existing_nullable=False)
    op.alter_column('ai_provider_reported_usage', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_providers', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('providers_slug_key', 'ai_providers', type_='unique')
    op.drop_index('ix_ai_providers_slug', table_name='ai_providers')
    op.create_index(op.f('ix_ai_providers_slug'), 'ai_providers', ['slug'], unique=True)
    op.add_column('ai_rate_limits', sa.Column('budget_usd', sa.Numeric(precision=10, scale=4), nullable=True, comment='Max dollar spend per month'))
    op.alter_column('ai_rate_limits', 'rpm',
               existing_type=sa.INTEGER(),
               comment='Requests per minute',
               existing_nullable=True)
    op.alter_column('ai_rate_limits', 'tpm',
               existing_type=sa.INTEGER(),
               comment='Tokens per minute',
               existing_nullable=True)
    op.alter_column('ai_rate_limits', 'rpd',
               existing_type=sa.INTEGER(),
               comment='Requests per day',
               existing_nullable=True)
    op.alter_column('ai_rate_limits', 'effective_date',
               existing_type=sa.DATE(),
               comment='The date from which this rate limit tier is effective.',
               existing_nullable=False)
    op.alter_column('ai_rate_limits', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_reconciliation_results', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_usage_logs', 'user_id',
               existing_type=sa.UUID(),
               server_default='00000000-0000-0000-0000-000000000000',
               existing_nullable=False)
    op.alter_column('ai_usage_logs', 'tokens_in',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_usage_logs', 'tokens_out',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_usage_logs', 'cost',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               server_default=None,
               comment='Cost in USD with high precision to handle fractional cent costs.',
               existing_nullable=False)
    op.alter_column('ai_usage_logs', 'status',
               existing_type=postgresql.ENUM('success', 'failed', name='call_status_enum'),
               server_default=None,
               existing_comment='Whether the API call succeeded or failed.',
               existing_nullable=False)
    op.alter_column('ai_usage_logs', 'project_tag',
               existing_type=sa.VARCHAR(length=200),
               comment='Optional tag for grouping usage by project, feature, or team.',
               existing_nullable=True)
    op.alter_column('ai_usage_logs', 'raw_response',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="Full raw usage payload from the provider. Stored for future reprocessing. On failed calls, contains {'error': '...', '_status': 'failed'}.",
               existing_nullable=True)
    op.alter_column('ai_usage_logs', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_ai_usage_logs_created_at', table_name='ai_usage_logs')
    op.add_column('ai_users', sa.Column('preferred_currency', sa.String(length=10), server_default='USD', nullable=False))
    op.alter_column('ai_users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_column('ai_users', 'preferred_currency')
    op.create_index('ix_ai_usage_logs_created_at', 'ai_usage_logs', ['created_at'], unique=False)
    op.alter_column('ai_usage_logs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('ai_usage_logs', 'raw_response',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment="Full raw usage payload from the provider. Stored for future reprocessing. On failed calls, contains {'error': '...', '_status': 'failed'}.",
               existing_nullable=True)
    op.alter_column('ai_usage_logs', 'project_tag',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Optional tag for grouping usage by project, feature, or team.',
               existing_nullable=True)
    op.alter_column('ai_usage_logs', 'status',
               existing_type=postgresql.ENUM('success', 'failed', name='call_status_enum'),
               server_default=sa.text("'success'::call_status_enum"),
               existing_comment='Whether the API call succeeded or failed.',
               existing_nullable=False)
    op.alter_column('ai_usage_logs', 'cost',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               server_default=sa.text("'0'::numeric"),
               comment=None,
               existing_comment='Cost in USD with high precision to handle fractional cent costs.',
               existing_nullable=False)
    op.alter_column('ai_usage_logs', 'tokens_out',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('ai_usage_logs', 'tokens_in',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('ai_usage_logs', 'user_id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_reconciliation_results', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('ai_rate_limits', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('ai_rate_limits', 'effective_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='The date from which this rate limit tier is effective.',
               existing_nullable=False)
    op.alter_column('ai_rate_limits', 'rpd',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Requests per day',
               existing_nullable=True)
    op.alter_column('ai_rate_limits', 'tpm',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Tokens per minute',
               existing_nullable=True)
    op.alter_column('ai_rate_limits', 'rpm',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Requests per minute',
               existing_nullable=True)
    op.drop_column('ai_rate_limits', 'budget_usd')
    op.drop_index(op.f('ix_ai_providers_slug'), table_name='ai_providers')
    op.create_index('ix_ai_providers_slug', 'ai_providers', ['slug'], unique=False)
    op.create_unique_constraint('providers_slug_key', 'ai_providers', ['slug'])
    op.alter_column('ai_providers', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('ai_provider_reported_usage', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('ai_provider_reported_usage', 'source',
               existing_type=sa.VARCHAR(length=200),
               server_default=sa.text("'api'::character varying"),
               comment=None,
               existing_comment='Which endpoint/method was used to fetch this data.',
               existing_nullable=False)
    op.alter_column('ai_provider_reported_usage', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this record was fetched from the provider API.',
               existing_nullable=False)
    op.alter_column('ai_provider_reported_usage', 'total_cost',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='Total cost (USD) as reported by the provider.',
               existing_nullable=True)
    op.alter_column('ai_provider_reported_usage', 'total_tokens',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Total tokens for the period as reported by the provider.',
               existing_nullable=True)
    op.alter_column('ai_provider_reported_usage', 'period_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='End of the usage period (UTC).',
               existing_nullable=False)
    op.alter_column('ai_provider_reported_usage', 'period_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Start of the usage period (UTC).',
               existing_nullable=False)
    op.alter_column('ai_job_runs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('ai_api_keys', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('ai_api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('ai_api_keys', 'label',
               existing_type=sa.VARCHAR(length=200),
               server_default=sa.text("'default'::character varying"),
               existing_nullable=False)
    op.alter_column('ai_api_keys', 'encrypted_key',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Fernet-encrypted provider API key. Never store plaintext here.',
               existing_nullable=False)
    op.alter_column('ai_api_keys', 'user_id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_alerts_sent', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    # ### end Alembic commands ###
