"""add_users_table

Revision ID: cd01f7ebba3c
Revises: 0003
Create Date: 2026-07-07 01:05:10.790220+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd01f7ebba3c'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Create users table
    op.create_table('ai_users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'ai_users', ['email'], unique=True)

    # 2. Insert default user for existing data
    # Hash of 'password' using passlib bcrypt for simplicity, though this is just a placeholder
    default_user_id = '00000000-0000-0000-0000-000000000000'
    op.execute(f"INSERT INTO users (id, email, hashed_password) VALUES ('{default_user_id}', 'admin@example.com', 'placeholder')")

    # 3. Add user_id to api_keys
    op.add_column('ai_api_keys', sa.Column('user_id', sa.Uuid(), server_default=default_user_id, nullable=False))
    op.create_index(op.f('ix_api_keys_user_id'), 'ai_api_keys', ['user_id'], unique=False)
    op.create_foreign_key(None, 'ai_api_keys', 'ai_users', ['user_id'], ['id'], ondelete='CASCADE')

    # 4. Add user_id to usage_logs
    op.add_column('ai_usage_logs', sa.Column('user_id', sa.Uuid(), server_default=default_user_id, nullable=False))
    op.create_index(op.f('ix_usage_logs_user_id'), 'ai_usage_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'ai_usage_logs', 'ai_users', ['user_id'], ['id'], ondelete='CASCADE')

    # Remove the server_default now that existing rows are populated
    op.alter_column('ai_api_keys', 'user_id', server_default=None)
    op.alter_column('ai_usage_logs', 'user_id', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_usage_logs', type_='foreignkey')
    op.drop_index(op.f('ix_usage_logs_user_id'), table_name='ai_usage_logs')
    op.create_index('ix_usage_logs_created_at', 'ai_usage_logs', ['created_at'], unique=False)
    op.alter_column('ai_usage_logs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('ai_usage_logs', 'raw_response',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment="Full raw usage payload from the provider. Stored for future reprocessing. On failed calls, contains {'error': '...', '_status': 'failed'}.",
               existing_nullable=True)
    op.alter_column('ai_usage_logs', 'project_tag',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Optional tag for grouping usage by project, feature, or team.',
               existing_nullable=True)
    op.alter_column('ai_usage_logs', 'status',
               existing_type=postgresql.ENUM('success', 'failed', name='call_status_enum'),
               server_default=sa.text("'success'::call_status_enum"),
               existing_comment='Whether the API call succeeded or failed.',
               existing_nullable=False)
    op.alter_column('ai_usage_logs', 'cost',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               server_default=sa.text("'0'::numeric"),
               comment=None,
               existing_comment='Cost in USD with high precision to handle fractional cent costs.',
               existing_nullable=False)
    op.alter_column('ai_usage_logs', 'tokens_out',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('ai_usage_logs', 'tokens_in',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_column('ai_usage_logs', 'user_id')
    op.alter_column('ai_reconciliation_results', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('ai_rate_limits', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('ai_rate_limits', 'effective_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='The date from which this rate limit tier is effective.',
               existing_nullable=False)
    op.alter_column('ai_rate_limits', 'rpd',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Requests per day',
               existing_nullable=True)
    op.alter_column('ai_rate_limits', 'tpm',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Tokens per minute',
               existing_nullable=True)
    op.alter_column('ai_rate_limits', 'rpm',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Requests per minute',
               existing_nullable=True)
    op.drop_index(op.f('ix_providers_slug'), table_name='ai_providers')
    op.create_index('ix_providers_slug', 'ai_providers', ['slug'], unique=False)
    op.create_unique_constraint('providers_slug_key', 'ai_providers', ['slug'])
    op.alter_column('ai_providers', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('ai_provider_reported_usage', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('ai_provider_reported_usage', 'source',
               existing_type=sa.VARCHAR(length=200),
               server_default=sa.text("'api'::character varying"),
               comment=None,
               existing_comment='Which endpoint/method was used to fetch this data.',
               existing_nullable=False)
    op.alter_column('ai_provider_reported_usage', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this record was fetched from the provider API.',
               existing_nullable=False)
    op.alter_column('ai_provider_reported_usage', 'total_cost',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='Total cost (USD) as reported by the provider.',
               existing_nullable=True)
    op.alter_column('ai_provider_reported_usage', 'total_tokens',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Total tokens for the period as reported by the provider.',
               existing_nullable=True)
    op.alter_column('ai_provider_reported_usage', 'period_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='End of the usage period (UTC).',
               existing_nullable=False)
    op.alter_column('ai_provider_reported_usage', 'period_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Start of the usage period (UTC).',
               existing_nullable=False)
    op.alter_column('ai_job_runs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_constraint(None, 'ai_api_keys', type_='foreignkey')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='ai_api_keys')
    op.alter_column('ai_api_keys', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('ai_api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('ai_api_keys', 'label',
               existing_type=sa.VARCHAR(length=200),
               server_default=sa.text("'default'::character varying"),
               existing_nullable=False)
    op.alter_column('ai_api_keys', 'encrypted_key',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Fernet-encrypted provider API key. Never store plaintext here.',
               existing_nullable=False)
    op.drop_column('ai_api_keys', 'user_id')
    op.alter_column('ai_alerts_sent', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='ai_users')
    op.drop_table('ai_users')
    # ### end Alembic commands ###
